# Copyright(C) 2021, Stamus Networks
# Written by RaphaÃ«l Brogat <rbrogat@stamus-networks.com>
#
# This file comes with ABSOLUTELY NO WARRANTY!
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '3.4'

networks:
  selks:

volumes:
  elastic-data:  #for ES data persistency
  suricata-rules: #for suricata rules transfer between scirius and suricata and for persistency
  scirius-data: #for scirius data persistency
  scirius-static: #statics files to be served by nginx
  suricata-run: #path where the suricata socket resides

services:
  
  elasticsearch:
    container_name: SELKS-elasticsearch
    image: elasticsearch:7.12.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      selks:
      
  kibana:
    container_name: SELKS-kibana
    image: kibana:7.12.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:5601 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      selks:
    
  logstash:
    container_name: SELKS-logstash
    image: logstash:7.12.0
    depends_on:
      scirius:
        condition: service_healthy #because we need to wait for scirius to populate ILM policy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9600 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ./containers-data/suricata/log:/var/log/suricata:ro
      - ./containers-data/logstash/conf.d/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./containers-data/logstash/templates/elasticsearch7-template.json:/usr/share/logstash/config/elasticsearch7-template.json
    networks:
      selks:
          
  suricata:
    container_name: SELKS-suricata
    image: jasonish/suricata:master-amd64
    entrypoint: /etc/suricata/new_entrypoint.sh
    restart: unless-stopped
    depends_on:
      scirius:
        condition: service_healthy
    environment:
      - SURICATA_OPTIONS=${INTERFACES} -vvv --set sensor-name=suricata
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    network_mode: host
    volumes:
       - ${SURICATA_LOGS_PATH:-./containers-data/suricata/log}:/var/log/suricata
       - suricata-rules:/etc/suricata/rules
       - suricata-run:/var/run/suricata/
       - ./containers-data/suricata/etc:/etc/suricata
    
  scirius:
    container_name: SELKS-scirius
    build:
      context: ./scirius
      args:
        VERSION: ${SCIRIUS_VERSION:-master}
    image: scirius:${SCIRIUS_VERSION:-master}
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SCIRIUS_SECRET_KEY}
      - DEBUG=${SCIRIUS_DEBUG:-False}
      - SCIRIUS_IN_SELKS=True
      - USE_ELASTICSEARCH=True
      - ELASTICSEARCH_ADDRESS=elasticsearch:9200 #Default
      - USE_KIBANA=True
      - KIBANA_URL=http://kibana:5601 #Default
      - KIBANA_PROXY=True #Get kibana proxied by Scirius
      - ALLOWED_HOSTS=* #allow connexions from anywhere
      - KIBANA7_DASHBOARDS_PATH=/opt/selks/kibana7-dashboards #where to find kibana dashboards
      - SURICATA_UNIX_SOCKET=/var/run/suricata/suricata-command.socket #socket to control suricata
      - USE_EVEBOX=True #gives access to evebox in the top menu
      - EVEBOX_ADDRESS=evebox:5636 #Default
      - USE_SURICATA_STATS=True #display more informations on the suricata page
      
    volumes:
      - scirius-static:/static/
      - scirius-data:/data/
      - ./containers-data/scirius/logs/:/logs/
      - suricata-rules:/rules
      - suricata-run:/var/run/suricata
      
    networks:
      selks:
          
  evebox:
    container_name: SELKS-evebox
    image: jasonish/evebox:master
    command: ["-e", "http://elasticsearch:9200"]
    restart: unless-stopped
    networks:
      selks:
        
  nginx:
    container_name: SELKS-nginx
    image: nginx
    command: ['${NGINX_EXEC:-nginx}', '-g', 'daemon off;']
    restart: unless-stopped
    volumes:
      - scirius-static:/static/:ro
      - ./containers-data/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./containers-data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./containers-data/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - 80:80
      - 443:443
    networks:
      selks:
